import type { Region } from "./types"

export const REGIONS: Region[] = [
  {
    id: "gulbarga",
    name: "Gulbarga (Kalaburagi)",
    lat: 17.33,
    lon: 76.82,
    state: "Karnataka",
    role: "Primary urad district",
    uradBelt: true,
  },
  {
    id: "bidar",
    name: "Bidar",
    lat: 17.91,
    lon: 77.52,
    state: "Karnataka",
    role: "Primary urad district",
    uradBelt: true,
  },
  {
    id: "latur",
    name: "Latur",
    lat: 18.4,
    lon: 76.56,
    state: "Maharashtra",
    role: "Major urad trading hub",
    uradBelt: true,
  },
  {
    id: "nanded",
    name: "Nanded",
    lat: 19.15,
    lon: 77.32,
    state: "Maharashtra",
    role: "Marathwada urad belt",
    uradBelt: true,
  },
  {
    id: "marathwada",
    name: "Marathwada (Aurangabad)",
    lat: 19.88,
    lon: 75.34,
    state: "Maharashtra",
    role: "Marathwada urad region",
    uradBelt: true,
  },
  {
    id: "vidarbha",
    name: "Vidarbha (Nagpur)",
    lat: 21.14,
    lon: 79.08,
    state: "Maharashtra",
    role: "Vidarbha urad region",
    uradBelt: true,
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    lat: 17.38,
    lon: 78.49,
    state: "Telangana",
    role: "Regional commodity hub",
    uradBelt: false,
  },
  {
    id: "chennai",
    name: "Chennai",
    lat: 13.08,
    lon: 80.27,
    state: "Tamil Nadu",
    role: "Trader base",
    uradBelt: false,
  },
]
